alias dbr='rake db:drop:all; rake db:create:all; rake db:migrate; rake db:test:prepare'
alias wip='cucumber --profile wip'
alias bu='bundle unlock'
alias bi='bundle install vendor/bundler_gems --relock'
alias bl='bundle lock'